---
title: "Stat 850 Project Proposal"
format: html
editor: visual
authors:
  - "Masha Mohammadi"
  - "Luka Milosevic"
---

## Data

### Source

The data we are using in this project comes from [TidyTuesday](https://github.com/rfordatascience/tidytuesday/blob/master/data/2023/2023-02-14/age_gaps.csv) website.

```{r, echo = FALSE, message = FALSE, warning = FALSE}
library(readr)
data <- read.csv("age_gaps.csv")
head(data)
```

### Description

This dataset compiles details about renowned actor couples with significant age differences, including information on the movies they co-starred in, release years, directors, and related attributes.

It was collected from TidyTuesday github repository, and was compiled from [Hollywood age gap site](https://hollywoodagegap.com/).

Here is a data dictionary showing each variable, the type of variable, units, and range of values that are possible:

+--------------------+-------------------------------------------------------+----------+----------+-------------------------+
| Name               | Description                                           | Type     | Units    | Range/Values            |
+====================+=======================================================+==========+==========+=========================+
| movie_name         | Name of the movie couples met and play in             | string   | NA       | NA                      |
+--------------------+-------------------------------------------------------+----------+----------+-------------------------+
| release year       | The year that movie released                          | numeric  | year     | 1935 - 2022             |
+--------------------+-------------------------------------------------------+----------+----------+-------------------------+
| director           | Name of the director of the movie                     | string   | NA       | NA                      |
+--------------------+-------------------------------------------------------+----------+----------+-------------------------+
| age_difference     | Difference of two partners' age                       | numeric  | year     | 0 - 52                  |
+--------------------+-------------------------------------------------------+----------+----------+-------------------------+
| couple_number      | number of couples play role in that movie.            | numeric  | person   | 1-7                     |
|                    |                                                       |          |          |                         |
|                    | It's been written like number 1 = ,,, number 2 = ,,,, |          |          |                         |
+--------------------+-------------------------------------------------------+----------+----------+-------------------------+
| actor_1_name       | name of the actor 1                                   | string   | NA       | NA                      |
+--------------------+-------------------------------------------------------+----------+----------+-------------------------+
| actor_2_name       | name of the actor 2                                   | string   | NA       | NA                      |
+--------------------+-------------------------------------------------------+----------+----------+-------------------------+
| character_1_gender | gender of the actor 1                                 | string   | NA       | woman / man             |
+--------------------+-------------------------------------------------------+----------+----------+-------------------------+
| character_2_gender | gender of the actor 2                                 | string   | NA       | woman / man             |
+--------------------+-------------------------------------------------------+----------+----------+-------------------------+
| actor_1_birthdate  | Birth date of actor 1                                 | date     | NA       | 1889-04-16 - 1996-06-01 |
+--------------------+-------------------------------------------------------+----------+----------+-------------------------+
| actor_2_birthdate  | Birth date of actor 2                                 | date     | NA       | 1906-10-06 - 1996-11-11 |
+--------------------+-------------------------------------------------------+----------+----------+-------------------------+
| actor_1_age        | Age of actor 1                                        | numeric  | year     | 18 - 81                 |
+--------------------+-------------------------------------------------------+----------+----------+-------------------------+
| actor_2_age        | Age of actor 2                                        | numeric  | year     | 17-68                   |
+--------------------+-------------------------------------------------------+----------+----------+-------------------------+

## Project Goals

Describe why this data is interesting and what you hope to do with it.

We will use [dataset](https://github.com/stat850-unl/project-marriage-story/blob/main/age_gaps.csv) to explore the following topics:

-   Is there a relationship between directors and the number of couples who start dating in their movies?

-   Is there a relationship between the year and the number of couples per movie? Did it become more common over the years or not?

-   Actors who tend to date their coworkers in movies.

-   Is there a relationship between the birth month of actors and the age difference with their partners?

-   Do men tend to date younger girls or older ones? What about women?

We expect to create

-   Several summary tables

-   Data visualization (age difference distribution, time series, director influence...)

-   Statistical tests (correlation, trends...)

## Project Teamwork Plan

It is important to note that both Masha and Luka will collaborate closely and divide the tasks as the work progresses. This is just a preliminary division.

**Phase 1: Data Preparation and Exploration**

1.  **Task Division:**
    -   Mahsa will set up the data analysis environment and prepare basic visualization.
    -   Luka will focus on data cleaning and initial exploration
2.  **Intermediate Deadline (Project Check-In 1):**
    -   Mahsa: Set up the analysis environment and produce basic data visualizations.
    -   Luka: Complete data cleaning and preliminary data summary.

**Phase 2: In-Depth Analysis**

3.  **Task Division:**
    -   Mahsa will explore relationships between variables and create advanced visualizations.
    -   Luka perform detailed statistical analysis.
4.  **Intermediate Deadline (Project Check-In 2):**
    -   Mahsa: Present advanced data visualizations and insights on relationships between variables.
    -   Luka: Share detailed statistical findings and any textual analysis results.

**Phase 3: Advanced Analysis and Insights**

5.  **Task Division:**
    -   Mahsa will focus on visualizing complex relationships and patterns within the data.
    -   Luka will delve into advanced data analysis techniques to extract insights from the dataset.
6.  **Intermediate Deadline (Project Check-In 3):**
    -   Mahsa: Present complex visualizations and patterns discovered in the data.
    -   Luka: Share the advanced data analysis findings and insights.

**Phase 4: Final Report and Presentation**

7.  **Task Division:**
    -   Mahsa and Luka will collaborate on creating the final project report, including key findings, visualizations, and conclusions.
    -   Together, we'll prepare the presentation for the project.
8.  **Final Deadline (Project Completion):**
    -   Submit the final project report and present our findings and insights to the Class.

## Additional Comments

What concerns do you have about this project? This is your place to provide feedback about the project guidelines and ask clarifying questions for me to address either individually or in class, if the question is relevant to everyone.




-----

Proposal feedback:

git fame output:

project-marriage-story$ git fame . --incl=".(q|R)md
"Processing: 100%|█████████████████████| 4/4 [00:00<00:00, 227.08file/s]
Total commits: 5
Total ctimes: 24
Total files: 6
Total loc: 395
| Author                |   loc |   coms |   fils |  distribution   |
|:----------------------|------:|-------:|-------:|:----------------|
| github-classroom[bot] |   288 |      1 |      4 | 72.9/20.0/66.7  |
| LukaUNL               |    88 |      2 |      1 | 22.3/40.0/16.7  |
| mahmhmmdi             |    19 |      2 |      1 | 4.8/40.0/16.7   |

